// V11 Master Data Array - Generated automatically from D4/G4
const apartmentsDataV11 = [
    {
        "id": "4-14R",
        "rank": 1,
        "lot": "103",
        "building": "14R",
        "aptText": "4",
        "floor": "1",
        "rooms": "3",
        "area": 86.41,
        "balcony": 11.76,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 954822.0,
        "aptType": "C 5",
        "imageFile": "floorplan_103_C_5.png"
    },
    {
        "id": "6-14R",
        "rank": 5,
        "lot": "103",
        "building": "14R",
        "aptText": "6",
        "floor": "2",
        "rooms": "3",
        "area": 86.41,
        "balcony": 14.14,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 962053.0,
        "aptType": "C 7",
        "imageFile": "floorplan_103_C_7.png"
    },
    {
        "id": "2-14R",
        "rank": 19,
        "lot": "103",
        "building": "14R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.71,
        "balcony": 53.35,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1080768.0,
        "aptType": "C 3",
        "imageFile": "floorplan_103_C_3.png"
    },
    {
        "id": "3-14R",
        "rank": 77,
        "lot": "103",
        "building": "14R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 126.83,
        "balcony": 17.51,
        "storage": 4.92,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1418815.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "5-14R",
        "rank": 90,
        "lot": "103",
        "building": "14R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.83,
        "balcony": 23.02,
        "storage": 4.92,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1439767.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "1-14R",
        "rank": 104,
        "lot": "103",
        "building": "14R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.92,
        "balcony": 50.7,
        "storage": 4.92,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1762079.0,
        "aptType": "A+ 3",
        "imageFile": "floorplan_103_A+_3.png"
    },
    {
        "id": "7-14R",
        "rank": 112,
        "lot": "103",
        "building": "14R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 160.04,
        "balcony": 92.27,
        "storage": 4.92,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1978291.0,
        "aptType": "D1",
        "imageFile": "floorplan_103_D1.png"
    },
    {
        "id": "4-8R",
        "rank": 2,
        "lot": "103",
        "building": "8R",
        "aptText": "4",
        "floor": "1",
        "rooms": "3",
        "area": 86.41,
        "balcony": 11.76,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 954822.0,
        "aptType": "C 5",
        "imageFile": "floorplan_103_C_5.png"
    },
    {
        "id": "6-8R",
        "rank": 4,
        "lot": "103",
        "building": "8R",
        "aptText": "6",
        "floor": "2",
        "rooms": "3",
        "area": 86.41,
        "balcony": 12.09,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 955809.0,
        "aptType": "C 7",
        "imageFile": "floorplan_103_C_7.png"
    },
    {
        "id": "2-8R",
        "rank": 17,
        "lot": "103",
        "building": "8R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.71,
        "balcony": 36.0,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1045627.0,
        "aptType": "C 1",
        "imageFile": "floorplan_103_C_1.png"
    },
    {
        "id": "3-8R",
        "rank": 76,
        "lot": "103",
        "building": "8R",
        "aptText": "3",
        "floor": "_2",
        "rooms": "1",
        "area": 5.0,
        "balcony": 126.83,
        "storage": 5.25,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1418815.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "5-8R",
        "rank": 89,
        "lot": "103",
        "building": "8R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.83,
        "balcony": 23.02,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1439748.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "1-8R",
        "rank": 108,
        "lot": "103",
        "building": "8R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.92,
        "balcony": 118.0,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1859047.0,
        "aptType": "A+",
        "imageFile": "floorplan_103_A+.png"
    },
    {
        "id": "7-8R",
        "rank": 114,
        "lot": "103",
        "building": "8R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 160.04,
        "balcony": 92.27,
        "storage": 4.923,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1978316.0,
        "aptType": "D1",
        "imageFile": "floorplan_103_D1.png"
    },
    {
        "id": "3-13R",
        "rank": 3,
        "lot": "103",
        "building": "13R",
        "aptText": "3",
        "floor": "1",
        "rooms": "3",
        "area": 86.41,
        "balcony": 11.76,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 954822.0,
        "aptType": "C 5",
        "imageFile": "floorplan_103_C_5.png"
    },
    {
        "id": "5-13R",
        "rank": 6,
        "lot": "103",
        "building": "13R",
        "aptText": "5",
        "floor": "2",
        "rooms": "3",
        "area": 86.41,
        "balcony": 14.22,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 962296.0,
        "aptType": "C 7",
        "imageFile": "floorplan_103_C_7.png"
    },
    {
        "id": "1-13R",
        "rank": 18,
        "lot": "103",
        "building": "13R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.71,
        "balcony": 52.85,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1079755.0,
        "aptType": "C 2",
        "imageFile": "floorplan_103_C_2.png"
    },
    {
        "id": "4-13R",
        "rank": 75,
        "lot": "103",
        "building": "13R",
        "aptText": "4",
        "floor": "_2",
        "rooms": "1",
        "area": 5.0,
        "balcony": 126.83,
        "storage": 5.25,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1418815.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "6-13R",
        "rank": 88,
        "lot": "103",
        "building": "13R",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 126.83,
        "balcony": 23.01,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1439729.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "2-13R",
        "rank": 103,
        "lot": "103",
        "building": "13R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.92,
        "balcony": 15.82,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1655819.0,
        "aptType": "A+ 2",
        "imageFile": "floorplan_103_A+_2.png"
    },
    {
        "id": "7-13R",
        "rank": 113,
        "lot": "103",
        "building": "13R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 160.04,
        "balcony": 92.28,
        "storage": 4.918,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1978308.0,
        "aptType": "D1",
        "imageFile": "floorplan_103_D1.png"
    },
    {
        "id": "4-7P",
        "rank": 7,
        "lot": "103",
        "building": "7P",
        "aptText": "4",
        "floor": "1",
        "rooms": "3",
        "area": 88.46,
        "balcony": 11.75,
        "storage": 5.855,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 975483.0,
        "aptType": "C 4",
        "imageFile": "floorplan_103_C_4.png"
    },
    {
        "id": "6-7P",
        "rank": 8,
        "lot": "103",
        "building": "7P",
        "aptText": "6",
        "floor": "2",
        "rooms": "3",
        "area": 88.46,
        "balcony": 14.33,
        "storage": 5.855,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 983340.0,
        "aptType": "C 6",
        "imageFile": "floorplan_103_C_6.png"
    },
    {
        "id": "2-7P",
        "rank": 20,
        "lot": "103",
        "building": "7P",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.57,
        "balcony": 56.3,
        "storage": 5.85,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 1085335.0,
        "aptType": "C",
        "imageFile": "floorplan_103_C.png"
    },
    {
        "id": "3-7P",
        "rank": 62,
        "lot": "103",
        "building": "7P",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 126.83,
        "balcony": 11.4,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 1395604.0,
        "aptType": "A 1",
        "imageFile": "floorplan_103_A_1.png"
    },
    {
        "id": "5-7P",
        "rank": 87,
        "lot": "103",
        "building": "7P",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.83,
        "balcony": 22.7,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 1438552.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "1-7P",
        "rank": 101,
        "lot": "103",
        "building": "7P",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "5",
        "area": 126.83,
        "balcony": 295.6,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 1618169.0,
        "aptType": "A",
        "imageFile": "floorplan_103_A.png"
    },
    {
        "id": "7-7P",
        "rank": 115,
        "lot": "103",
        "building": "7P",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 160.04,
        "balcony": 94.94,
        "storage": 4.92,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "15",
        "price": 1981704.0,
        "aptType": "D1",
        "imageFile": "floorplan_103_D1.png"
    },
    {
        "id": "8-3T",
        "rank": 9,
        "lot": "102",
        "building": "3T",
        "aptText": "8",
        "floor": "3",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.85,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003619.0,
        "aptType": "C 1",
        "imageFile": "floorplan_102_C_1.png"
    },
    {
        "id": "4-3T",
        "rank": 10,
        "lot": "102",
        "building": "3T",
        "aptText": "4",
        "floor": "1",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.85,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003619.0,
        "aptType": "C 1",
        "imageFile": "floorplan_102_C_1.png"
    },
    {
        "id": "6-3T",
        "rank": 15,
        "lot": "102",
        "building": "3T",
        "aptText": "6",
        "floor": "2",
        "rooms": "3",
        "area": 92.12,
        "balcony": 17.84,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1021833.0,
        "aptType": "C 2",
        "imageFile": "floorplan_102_C_2.png"
    },
    {
        "id": "2-3T",
        "rank": 22,
        "lot": "102",
        "building": "3T",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 92.12,
        "balcony": 66.58,
        "storage": 5.224,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1129654.0,
        "aptType": "C 3",
        "imageFile": "floorplan_102_C_3.png"
    },
    {
        "id": "7-3T",
        "rank": 66,
        "lot": "102",
        "building": "3T",
        "aptText": "7",
        "floor": "3",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.04,
        "storage": 6.437,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1404887.0,
        "aptType": "E 1",
        "imageFile": "floorplan_102_E_1.png"
    },
    {
        "id": "3-3T",
        "rank": 67,
        "lot": "102",
        "building": "3T",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.04,
        "storage": 6.437,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1404887.0,
        "aptType": "E 1",
        "imageFile": "floorplan_102_E_1.png"
    },
    {
        "id": "5-3T",
        "rank": 85,
        "lot": "102",
        "building": "3T",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.75,
        "balcony": 19.47,
        "storage": 6.437,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1433107.0,
        "aptType": "E 2",
        "imageFile": "floorplan_102_E_2.png"
    },
    {
        "id": "1-3T",
        "rank": 96,
        "lot": "102",
        "building": "3T",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "5",
        "area": 126.25,
        "balcony": 52.38,
        "storage": 5.204,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1518050.0,
        "aptType": "E 3",
        "imageFile": "floorplan_102_E_3.png"
    },
    {
        "id": "9-3T",
        "rank": 123,
        "lot": "102",
        "building": "3T",
        "aptText": "9",
        "floor": "4",
        "rooms": "6",
        "area": 178.97,
        "balcony": 67.15,
        "storage": 6.708,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 2184643.0,
        "aptType": "D",
        "imageFile": "floorplan_102_D.png"
    },
    {
        "id": "4-6T",
        "rank": 11,
        "lot": "102",
        "building": "6T",
        "aptText": "4",
        "floor": "1",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.85,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003631.0,
        "aptType": "C 1",
        "imageFile": "floorplan_102_C_1.png"
    },
    {
        "id": "6-6T",
        "rank": 12,
        "lot": "102",
        "building": "6T",
        "aptText": "6",
        "floor": "2",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.85,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003631.0,
        "aptType": "C 2",
        "imageFile": "floorplan_102_C_2.png"
    },
    {
        "id": "2-6T",
        "rank": 25,
        "lot": "102",
        "building": "6T",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 92.12,
        "balcony": 90.63,
        "storage": 5.224,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1154010.0,
        "aptType": "C 3",
        "imageFile": "floorplan_102_C_3.png"
    },
    {
        "id": "5-6T",
        "rank": 68,
        "lot": "102",
        "building": "6T",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.05,
        "storage": 6.445,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1404969.0,
        "aptType": "E 2",
        "imageFile": "floorplan_102_E_2.png"
    },
    {
        "id": "3-6T",
        "rank": 71,
        "lot": "102",
        "building": "6T",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.09,
        "storage": 6.445,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1405117.0,
        "aptType": "E 1",
        "imageFile": "floorplan_102_E_1.png"
    },
    {
        "id": "1-6T",
        "rank": 99,
        "lot": "102",
        "building": "6T",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "5",
        "area": 126.25,
        "balcony": 113.63,
        "storage": 5.204,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1605232.0,
        "aptType": "E 3",
        "imageFile": "floorplan_102_E_3.png"
    },
    {
        "id": "7-6T",
        "rank": 122,
        "lot": "102",
        "building": "6T",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 178.97,
        "balcony": 67.15,
        "storage": 6.666,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 2159093.0,
        "aptType": "D",
        "imageFile": "floorplan_102_D.png"
    },
    {
        "id": "7-1T",
        "rank": 13,
        "lot": "102",
        "building": "1T",
        "aptText": "7",
        "floor": "3",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.86,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003656.0,
        "aptType": "C 1",
        "imageFile": "floorplan_102_C_1.png"
    },
    {
        "id": "3-1T",
        "rank": 14,
        "lot": "102",
        "building": "1T",
        "aptText": "3",
        "floor": "1",
        "rooms": "3",
        "area": 92.12,
        "balcony": 11.86,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1003656.0,
        "aptType": "C 1",
        "imageFile": "floorplan_102_C_1.png"
    },
    {
        "id": "5-1T",
        "rank": 16,
        "lot": "102",
        "building": "1T",
        "aptText": "5",
        "floor": "2",
        "rooms": "3",
        "area": 92.12,
        "balcony": 17.88,
        "storage": 4.373,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1021949.0,
        "aptType": "C 2",
        "imageFile": "floorplan_102_C_2.png"
    },
    {
        "id": "1-1T",
        "rank": 38,
        "lot": "102",
        "building": "1T",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "3",
        "area": 92.12,
        "balcony": 152.6,
        "storage": 5.224,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1183754.0,
        "aptType": "C",
        "imageFile": "floorplan_102_C.png"
    },
    {
        "id": "4-1T",
        "rank": 69,
        "lot": "102",
        "building": "1T",
        "aptText": "4",
        "floor": "1",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.05,
        "storage": 6.445,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1404973.0,
        "aptType": "E 1",
        "imageFile": "floorplan_102_E_1.png"
    },
    {
        "id": "8-1T",
        "rank": 70,
        "lot": "102",
        "building": "1T",
        "aptText": "8",
        "floor": "3",
        "rooms": "5",
        "area": 126.75,
        "balcony": 12.05,
        "storage": 6.445,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1404973.0,
        "aptType": "E 1",
        "imageFile": "floorplan_102_E_1.png"
    },
    {
        "id": "6-1T",
        "rank": 86,
        "lot": "102",
        "building": "1T",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 126.75,
        "balcony": 19.46,
        "storage": 6.445,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1433114.0,
        "aptType": "E 2",
        "imageFile": "floorplan_102_E_2.png"
    },
    {
        "id": "2-1T",
        "rank": 97,
        "lot": "102",
        "building": "1T",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "5",
        "area": 126.25,
        "balcony": 79.97,
        "storage": 5.204,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 1562622.0,
        "aptType": "E",
        "imageFile": "floorplan_102_E.png"
    },
    {
        "id": "9-1T",
        "rank": 124,
        "lot": "102",
        "building": "1T",
        "aptText": "9",
        "floor": "4",
        "rooms": "6",
        "area": 178.97,
        "balcony": 67.16,
        "storage": 6.708,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "22",
        "price": 2184657.0,
        "aptType": "D",
        "imageFile": "floorplan_102_D.png"
    },
    {
        "id": "1-9R",
        "rank": 21,
        "lot": "103",
        "building": "9R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.34,
        "balcony": 71.2,
        "storage": 5.433,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1100154.0,
        "aptType": "C-",
        "imageFile": "floorplan_103_C-.png"
    },
    {
        "id": "4-9R",
        "rank": 28,
        "lot": "103",
        "building": "9R",
        "aptText": "4",
        "floor": "1",
        "rooms": "4",
        "area": 107.69,
        "balcony": 11.56,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1163822.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "6-9R",
        "rank": 33,
        "lot": "103",
        "building": "9R",
        "aptText": "6",
        "floor": "2",
        "rooms": "4",
        "area": 107.69,
        "balcony": 14.48,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1172690.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "2-9R",
        "rank": 51,
        "lot": "103",
        "building": "9R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "4",
        "area": 107.66,
        "balcony": 38.86,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1246856.0,
        "aptType": "B",
        "imageFile": "floorplan_103_B.png"
    },
    {
        "id": "3-9R",
        "rank": 58,
        "lot": "103",
        "building": "9R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 124.88,
        "balcony": 11.74,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1375916.0,
        "aptType": "A 3",
        "imageFile": "floorplan_103_A_3.png"
    },
    {
        "id": "5-9R",
        "rank": 60,
        "lot": "103",
        "building": "9R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 124.88,
        "balcony": 14.86,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1387761.0,
        "aptType": "A 6",
        "imageFile": "floorplan_103_A_6.png"
    },
    {
        "id": "7-9R",
        "rank": 119,
        "lot": "103",
        "building": "9R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 159.8,
        "balcony": 115.91,
        "storage": 4.91,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 2005629.0,
        "aptType": "D",
        "imageFile": "floorplan_103_D.png"
    },
    {
        "id": "2-12R",
        "rank": 23,
        "lot": "103",
        "building": "12R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.34,
        "balcony": 114.36,
        "storage": 5.433,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1143863.0,
        "aptType": "C- 1",
        "imageFile": "floorplan_103_C-_1.png"
    },
    {
        "id": "3-12R",
        "rank": 26,
        "lot": "103",
        "building": "12R",
        "aptText": "3",
        "floor": "1",
        "rooms": "4",
        "area": 107.69,
        "balcony": 11.56,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1163822.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "5-12R",
        "rank": 32,
        "lot": "103",
        "building": "12R",
        "aptText": "5",
        "floor": "2",
        "rooms": "4",
        "area": 107.69,
        "balcony": 14.32,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1172207.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "1-12R",
        "rank": 52,
        "lot": "103",
        "building": "12R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "4",
        "area": 107.75,
        "balcony": 39.35,
        "storage": 4.397,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1274453.0,
        "aptType": "B 2",
        "imageFile": "floorplan_103_B_2.png"
    },
    {
        "id": "4-12R",
        "rank": 57,
        "lot": "103",
        "building": "12R",
        "aptText": "4",
        "floor": "1",
        "rooms": "5",
        "area": 124.88,
        "balcony": 11.74,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1375912.0,
        "aptType": "A 3",
        "imageFile": "floorplan_103_A_3.png"
    },
    {
        "id": "6-12R",
        "rank": 74,
        "lot": "103",
        "building": "12R",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 124.88,
        "balcony": 23.04,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1418815.0,
        "aptType": "A 6",
        "imageFile": "floorplan_103_A_6.png"
    },
    {
        "id": "7-12R",
        "rank": 116,
        "lot": "103",
        "building": "12R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 158.89,
        "balcony": 111.11,
        "storage": 4.925,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1989837.0,
        "aptType": "D2",
        "imageFile": "floorplan_103_D2.png"
    },
    {
        "id": "1-15R",
        "rank": 24,
        "lot": "103",
        "building": "15R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "3",
        "area": 88.34,
        "balcony": 123.7,
        "storage": 5.43,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1149575.0,
        "aptType": "C- 2",
        "imageFile": "floorplan_103_C-_2.png"
    },
    {
        "id": "4-15R",
        "rank": 27,
        "lot": "103",
        "building": "15R",
        "aptText": "4",
        "floor": "1",
        "rooms": "4",
        "area": 107.69,
        "balcony": 11.56,
        "storage": 4.4,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1163822.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "6-15R",
        "rank": 34,
        "lot": "103",
        "building": "15R",
        "aptText": "6",
        "floor": "2",
        "rooms": "4",
        "area": 107.69,
        "balcony": 14.56,
        "storage": 4.4,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1172936.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "2-15R",
        "rank": 55,
        "lot": "103",
        "building": "15R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "4",
        "area": 107.75,
        "balcony": 70.2,
        "storage": 4.4,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1339647.0,
        "aptType": "B 3",
        "imageFile": "floorplan_103_B_3.png"
    },
    {
        "id": "3-15R",
        "rank": 56,
        "lot": "103",
        "building": "15R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 124.88,
        "balcony": 11.74,
        "storage": 4.92,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1375901.0,
        "aptType": "A 3",
        "imageFile": "floorplan_103_A_3.png"
    },
    {
        "id": "5-15R",
        "rank": 61,
        "lot": "103",
        "building": "15R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 124.88,
        "balcony": 14.96,
        "storage": 4.92,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1388134.0,
        "aptType": "A 6",
        "imageFile": "floorplan_103_A_6.png"
    },
    {
        "id": "7-15R",
        "rank": 120,
        "lot": "103",
        "building": "15R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 159.8,
        "balcony": 115.91,
        "storage": 4.91,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 2005629.0,
        "aptType": "D",
        "imageFile": "floorplan_103_D.png"
    },
    {
        "id": "3-10R",
        "rank": 29,
        "lot": "103",
        "building": "10R",
        "aptText": "3",
        "floor": "1",
        "rooms": "4",
        "area": 107.72,
        "balcony": 11.76,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1164633.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "5-10R",
        "rank": 37,
        "lot": "103",
        "building": "10R",
        "aptText": "5",
        "floor": "2",
        "rooms": "4",
        "area": 107.72,
        "balcony": 14.6,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1173255.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "1-10R",
        "rank": 50,
        "lot": "103",
        "building": "10R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "4",
        "area": 106.92,
        "balcony": 38.86,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1237402.0,
        "aptType": "B 1",
        "imageFile": "floorplan_103_B_1.png"
    },
    {
        "id": "4-10R",
        "rank": 79,
        "lot": "103",
        "building": "10R",
        "aptText": "4",
        "floor": "1",
        "rooms": "5",
        "area": 126.93,
        "balcony": 17.9,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1421392.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "6-10R",
        "rank": 92,
        "lot": "103",
        "building": "10R",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 126.93,
        "balcony": 22.99,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1440722.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "2-10R",
        "rank": 105,
        "lot": "103",
        "building": "10R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.94,
        "balcony": 54.88,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 1772791.0,
        "aptType": "A+ 1",
        "imageFile": "floorplan_103_A+_1.png"
    },
    {
        "id": "7-10R",
        "rank": 118,
        "lot": "103",
        "building": "10R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 159.8,
        "balcony": 115.91,
        "storage": 4.91,
        "isLast": true,
        "sunDir": "חמה",
        "parkingDist": "12",
        "price": 2005629.0,
        "aptType": "D",
        "imageFile": "floorplan_103_D.png"
    },
    {
        "id": "4-11R",
        "rank": 30,
        "lot": "103",
        "building": "11R",
        "aptText": "4",
        "floor": "1",
        "rooms": "4",
        "area": 107.72,
        "balcony": 11.76,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1164633.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "6-11R",
        "rank": 35,
        "lot": "103",
        "building": "11R",
        "aptText": "6",
        "floor": "2",
        "rooms": "4",
        "area": 107.72,
        "balcony": 14.54,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1173094.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "2-11R",
        "rank": 49,
        "lot": "103",
        "building": "11R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "4",
        "area": 106.92,
        "balcony": 36.86,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1232339.0,
        "aptType": "B 1",
        "imageFile": "floorplan_103_B_1.png"
    },
    {
        "id": "3-11R",
        "rank": 78,
        "lot": "103",
        "building": "11R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 126.93,
        "balcony": 17.9,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1421388.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "5-11R",
        "rank": 91,
        "lot": "103",
        "building": "11R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 126.93,
        "balcony": 22.97,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1440654.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "1-11R",
        "rank": 106,
        "lot": "103",
        "building": "11R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.94,
        "balcony": 54.88,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1772791.0,
        "aptType": "A+ 1",
        "imageFile": "floorplan_103_A+_1.png"
    },
    {
        "id": "7-11R",
        "rank": 117,
        "lot": "103",
        "building": "11R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 159.8,
        "balcony": 115.91,
        "storage": 4.91,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 2005629.0,
        "aptType": "D",
        "imageFile": "floorplan_103_D.png"
    },
    {
        "id": "3-16R",
        "rank": 31,
        "lot": "103",
        "building": "16R",
        "aptText": "3",
        "floor": "1",
        "rooms": "4",
        "area": 107.72,
        "balcony": 11.76,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1164633.0,
        "aptType": "B-",
        "imageFile": "floorplan_103_B-.png"
    },
    {
        "id": "5-16R",
        "rank": 36,
        "lot": "103",
        "building": "16R",
        "aptText": "5",
        "floor": "2",
        "rooms": "4",
        "area": 107.72,
        "balcony": 14.55,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1173121.0,
        "aptType": "B- 1",
        "imageFile": "floorplan_103_B-_1.png"
    },
    {
        "id": "1-16R",
        "rank": 54,
        "lot": "103",
        "building": "16R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "4",
        "area": 106.92,
        "balcony": 59.0,
        "storage": 4.385,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1313711.0,
        "aptType": "B 4",
        "imageFile": "floorplan_103_B_4.png"
    },
    {
        "id": "4-16R",
        "rank": 80,
        "lot": "103",
        "building": "16R",
        "aptText": "4",
        "floor": "1",
        "rooms": "5",
        "area": 126.94,
        "balcony": 17.91,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1421444.0,
        "aptType": "A 2",
        "imageFile": "floorplan_103_A_2.png"
    },
    {
        "id": "6-16R",
        "rank": 93,
        "lot": "103",
        "building": "16R",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 126.94,
        "balcony": 22.99,
        "storage": 4.922,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1440748.0,
        "aptType": "A 5",
        "imageFile": "floorplan_103_A_5.png"
    },
    {
        "id": "2-16R",
        "rank": 107,
        "lot": "103",
        "building": "16R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "6",
        "area": 145.94,
        "balcony": 90.6,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1824491.0,
        "aptType": "A+ 4",
        "imageFile": "floorplan_103_A+_4.png"
    },
    {
        "id": "7-16R",
        "rank": 121,
        "lot": "103",
        "building": "16R",
        "aptText": "7",
        "floor": "3",
        "rooms": "6",
        "area": 159.8,
        "balcony": 117.65,
        "storage": 4.91,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 2007839.0,
        "aptType": "D",
        "imageFile": "floorplan_103_D.png"
    },
    {
        "id": "6-2R",
        "rank": 39,
        "lot": "102",
        "building": "2R",
        "aptText": "6",
        "floor": "2",
        "rooms": "4",
        "area": 111.38,
        "balcony": 11.57,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1196182.0,
        "aptType": "B 2",
        "imageFile": "floorplan_102_B_2.png"
    },
    {
        "id": "10-2R",
        "rank": 42,
        "lot": "102",
        "building": "2R",
        "aptText": "10",
        "floor": "4",
        "rooms": "4",
        "area": 111.38,
        "balcony": 11.78,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1196814.0,
        "aptType": "B 2",
        "imageFile": "floorplan_102_B_2.png"
    },
    {
        "id": "8-2R",
        "rank": 45,
        "lot": "102",
        "building": "2R",
        "aptText": "8",
        "floor": "3",
        "rooms": "4",
        "area": 111.38,
        "balcony": 14.48,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1206260.0,
        "aptType": "B 3",
        "imageFile": "floorplan_102_B_3.png"
    },
    {
        "id": "4-2R",
        "rank": 48,
        "lot": "102",
        "building": "2R",
        "aptText": "4",
        "floor": "1",
        "rooms": "4",
        "area": 111.38,
        "balcony": 16.71,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1214759.0,
        "aptType": "B 1",
        "imageFile": "floorplan_102_B_1.png"
    },
    {
        "id": "2-2R",
        "rank": 53,
        "lot": "102",
        "building": "2R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "4",
        "area": 114.66,
        "balcony": 34.11,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1310972.0,
        "aptType": "B",
        "imageFile": "floorplan_102_B.png"
    },
    {
        "id": "3-2R",
        "rank": 65,
        "lot": "102",
        "building": "2R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 127.17,
        "balcony": 11.72,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1400410.0,
        "aptType": "A 1",
        "imageFile": "floorplan_102_A_1.png"
    },
    {
        "id": "7-2R",
        "rank": 81,
        "lot": "102",
        "building": "2R",
        "aptText": "7",
        "floor": "3",
        "rooms": "5",
        "area": 127.17,
        "balcony": 17.94,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1424035.0,
        "aptType": "A 4",
        "imageFile": "floorplan_102_A_4.png"
    },
    {
        "id": "5-2R",
        "rank": 94,
        "lot": "102",
        "building": "2R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 127.17,
        "balcony": 23.16,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1443848.0,
        "aptType": "A 2",
        "imageFile": "floorplan_102_A_2.png"
    },
    {
        "id": "9-2R",
        "rank": 95,
        "lot": "102",
        "building": "2R",
        "aptText": "9",
        "floor": "4",
        "rooms": "5",
        "area": 127.17,
        "balcony": 23.16,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1443848.0,
        "aptType": "A 2",
        "imageFile": "floorplan_102_A_2.png"
    },
    {
        "id": "1-2R",
        "rank": 98,
        "lot": "102",
        "building": "2R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "5",
        "area": 127.17,
        "balcony": 93.83,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1588623.0,
        "aptType": "A",
        "imageFile": "floorplan_102_A.png"
    },
    {
        "id": "11-2R",
        "rank": 111,
        "lot": "102",
        "building": "2R",
        "aptText": "11",
        "floor": "5",
        "rooms": "6",
        "area": 156.09,
        "balcony": 115.79,
        "storage": 4.921,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1965578.0,
        "aptType": "D3",
        "imageFile": "floorplan_102_D3.png"
    },
    {
        "id": "6-5R",
        "rank": 40,
        "lot": "102",
        "building": "5R",
        "aptText": "6",
        "floor": "2",
        "rooms": "4",
        "area": 111.38,
        "balcony": 11.57,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1196182.0,
        "aptType": "B 3",
        "imageFile": "floorplan_102_B_3.png"
    },
    {
        "id": "8-5R",
        "rank": 44,
        "lot": "102",
        "building": "5R",
        "aptText": "8",
        "floor": "3",
        "rooms": "4",
        "area": 111.38,
        "balcony": 14.47,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1206233.0,
        "aptType": "B 2",
        "imageFile": "floorplan_102_B_2.png"
    },
    {
        "id": "4-5R",
        "rank": 47,
        "lot": "102",
        "building": "5R",
        "aptText": "4",
        "floor": "1",
        "rooms": "4",
        "area": 111.38,
        "balcony": 16.71,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1214729.0,
        "aptType": "B 2",
        "imageFile": "floorplan_102_B_2.png"
    },
    {
        "id": "3-5R",
        "rank": 63,
        "lot": "102",
        "building": "5R",
        "aptText": "3",
        "floor": "1",
        "rooms": "5",
        "area": 127.17,
        "balcony": 11.72,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1400410.0,
        "aptType": "A 2",
        "imageFile": "floorplan_102_A_2.png"
    },
    {
        "id": "5-5R",
        "rank": 72,
        "lot": "102",
        "building": "5R",
        "aptText": "5",
        "floor": "2",
        "rooms": "5",
        "area": 127.17,
        "balcony": 14.74,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1411890.0,
        "aptType": "A 4",
        "imageFile": "floorplan_102_A_4.png"
    },
    {
        "id": "7-5R",
        "rank": 83,
        "lot": "102",
        "building": "5R",
        "aptText": "7",
        "floor": "3",
        "rooms": "5",
        "area": 127.17,
        "balcony": 17.94,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1424035.0,
        "aptType": "A 2",
        "imageFile": "floorplan_102_A_2.png"
    },
    {
        "id": "2-5R",
        "rank": 84,
        "lot": "102",
        "building": "5R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "4",
        "area": 114.66,
        "balcony": 98.48,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1425233.0,
        "aptType": "B 4",
        "imageFile": "floorplan_102_B_4.png"
    },
    {
        "id": "1-5R",
        "rank": 102,
        "lot": "102",
        "building": "5R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "5",
        "area": 127.17,
        "balcony": 138.3,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1621752.0,
        "aptType": "A 6",
        "imageFile": "floorplan_102_A_6.png"
    },
    {
        "id": "9-5R",
        "rank": 109,
        "lot": "102",
        "building": "5R",
        "aptText": "9",
        "floor": "4",
        "rooms": "6",
        "area": 156.09,
        "balcony": 115.79,
        "storage": 4.921,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1965578.0,
        "aptType": "D3",
        "imageFile": "floorplan_102_D3.png"
    },
    {
        "id": "5-4R",
        "rank": 41,
        "lot": "102",
        "building": "4R",
        "aptText": "5",
        "floor": "2",
        "rooms": "4",
        "area": 111.38,
        "balcony": 11.57,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1196194.0,
        "aptType": "B 2",
        "imageFile": "floorplan_102_B_2.png"
    },
    {
        "id": "7-4R",
        "rank": 43,
        "lot": "102",
        "building": "4R",
        "aptText": "7",
        "floor": "3",
        "rooms": "4",
        "area": 111.38,
        "balcony": 14.47,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1206233.0,
        "aptType": "B 3",
        "imageFile": "floorplan_102_B_3.png"
    },
    {
        "id": "3-4R",
        "rank": 46,
        "lot": "102",
        "building": "4R",
        "aptText": "3",
        "floor": "1",
        "rooms": "4",
        "area": 111.38,
        "balcony": 16.71,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1214729.0,
        "aptType": "B 1",
        "imageFile": "floorplan_102_B_1.png"
    },
    {
        "id": "1-4R",
        "rank": 59,
        "lot": "102",
        "building": "4R",
        "aptText": "1",
        "floor": "קרקע",
        "rooms": "4",
        "area": 114.66,
        "balcony": 68.08,
        "storage": 3.687,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1386749.0,
        "aptType": "B 4",
        "imageFile": "floorplan_102_B_4.png"
    },
    {
        "id": "4-4R",
        "rank": 64,
        "lot": "102",
        "building": "4R",
        "aptText": "4",
        "floor": "1",
        "rooms": "5",
        "area": 127.17,
        "balcony": 11.72,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1400410.0,
        "aptType": "A 1",
        "imageFile": "floorplan_102_A_1.png"
    },
    {
        "id": "6-4R",
        "rank": 73,
        "lot": "102",
        "building": "4R",
        "aptText": "6",
        "floor": "2",
        "rooms": "5",
        "area": 127.17,
        "balcony": 14.74,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1411905.0,
        "aptType": "A 2",
        "imageFile": "floorplan_102_A_2.png"
    },
    {
        "id": "8-4R",
        "rank": 82,
        "lot": "102",
        "building": "4R",
        "aptText": "8",
        "floor": "3",
        "rooms": "5",
        "area": 127.17,
        "balcony": 17.94,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1424035.0,
        "aptType": "A 4",
        "imageFile": "floorplan_102_A_4.png"
    },
    {
        "id": "2-4R",
        "rank": 100,
        "lot": "102",
        "building": "4R",
        "aptText": "2",
        "floor": "קרקע",
        "rooms": "5",
        "area": 127.17,
        "balcony": 116.51,
        "storage": 4.921,
        "isLast": false,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1617334.0,
        "aptType": "A 5",
        "imageFile": "floorplan_102_A_5.png"
    },
    {
        "id": "9-4R",
        "rank": 110,
        "lot": "102",
        "building": "4R",
        "aptText": "9",
        "floor": "4",
        "rooms": "6",
        "area": 156.09,
        "balcony": 115.79,
        "storage": 4.921,
        "isLast": true,
        "sunDir": "קרירה",
        "parkingDist": "12",
        "price": 1965578.0,
        "aptType": "D3",
        "imageFile": "floorplan_102_D3.png"
    }
];
